### ISSUE TITLE
Mudul-IDs anzeigen

### ISSUE THREAD

**Issue by Anke** [e-spin/contao_dcaconfig-editor#2]
Hallo Ingolf,

die Erweiterung läuft unter Contao 3.5, allerdings werden mir die Modul-IDs mit diesem Beispielcode nicht mehr angezeigt:

<code>$GLOBALS['TL_DCA']['tl_module']['list']['label']['fields'][] = 'id';</code>
<code>$GLOBALS['TL_DCA']['tl_module']['list']['label']['format'] = '%s <span style="font-weight:normal; padding-left: 3px;">(IDm: %s)</span>';</code>

Ich komme leider nicht darauf, was geändert werden müsste.

VG
Anke

**Comment by e-spin** [comment]
Die Anzeige der Modul-IDs ist leider nicht so einfach per DCA zu bewerkstelligen - siehe
https://community.contao.org/de/showthread.php?15614-Gel%F6st-Wie-die-Seiten-Artikel-und-AUCH-Modul-ID-sichtbar-im-Backend-anzeigen
